blog/urls.py
from django.urls import path
from .views import home, api

app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('api', api, name="api")
]

blog2/urls.py
from django.urls import path, re_path
from .views import home, article_detail

app_name = "blog2"

urlpatterns = [
    path('home', home, name='home'),
    path('article/<slug:slug>', article_detail, name='article_detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('blog2.urls')),
    path('', include('blog3.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog2/models.py
from django.db import models

# Create your models here.

blog2/views.py
from django.shortcuts import render

from blog.models import Article


def home(request):
    context = {
        "articles": Article.objects.filter(status='p').order_by("-publish")[:3]
    }
    return render(request, "home.html", context)


def article_detail(request, slug):
    context = {
        "article": Article.objects.get(slug=slug)
    }
    return render(request, "article_detail.html", context)

# Create your views here.

blog2/templates/article_detail.html
<article>
    <img src="{{article.thumbnail.url}}" alt="article.title" width="300" height="auto">
    <h1>{{article.title}}</h1>
    <small>{{article.publish}}</small>
    <p>{{article.description}}</p>
</article>

blog2/templates/home.html
<center>
    {% for article in articles %}
        <article>
            <img src="{{article.thumbnail.url}}" alt="article.title" width="300" height="auto">
            <h1><a href="{% url 'blog2:article_detail' article.slug %}">{{article.title}}</a></h1>
            <small>{{article.publish}}</small>
            <p>{{article.description}}</p>
        </article>
    {% endfor %}
</center>