blog/urls.py
from django.urls import path
from .views import home, api

app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('api', api, name="api")
]

blog3/urls.py
from django.urls import path
from .views import ArticleDetail, ArticleList, CategoryList, AuthorList

app_name = "blog3"

urlpatterns = [
    path('blog3/home', ArticleList.as_view(), name='home'),
    path('blog3/home/page/<int:page>', ArticleList.as_view(), name='home'),
    path('blog3/detail.html/<slug:slug>', ArticleDetail.as_view(), name='article_details'),
    path('blog3/category/<slug:slug>', CategoryList.as_view(), name='category'),
    path('blog3/category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name='category'),
    path('blog3/author/<slug:username>', AuthorList.as_view(), name='author'),
    path('blog3/author/<slug:username>/page/<int:page>', AuthorList.as_view(), name='author')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('blog2.urls')),
    path('', include('blog3.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog3/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.html import format_html
from extensions.utils import jalali_convertor
from django.urls import reverse


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active_category(self):
        return self.filter(status=True)


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان دسته‌بندی')
    slug = models.CharField(max_length=100, verbose_name='آدرس دسته‌بندی')
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='children', verbose_name='زیردسته')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی‌ها'
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),
        ('p', 'منتشر شده')
    )
    title = models.CharField(max_length=200, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    category = models.ManyToManyField(Category, verbose_name='دسته‌بندی', related_name="articles")
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    description = models.TextField(verbose_name='شرح مقاله')
    thumbnail = models.ImageField(upload_to="images", verbose_name='تصویر مقاله')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = "مقالات"
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('account:home')

    def jalali_publish(self):
        return jalali_convertor(self.publish)

    jalali_publish.short_description = 'زمان انتشار'

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html(f"<img width=100 style='border-radius:20px' src='{self.thumbnail.url}'>")

    thumbnail_tag.short_description = "عکس"

    def category_to_str(self):
        # return ', '.join([category.title for category in obj.category.all()])
        return ', '.join([category.title for category in self.category.active_category()])
    category_to_str.short_description = 'دسته‌بندی'

    objects = ArticleManager()

blog3/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from .models import Category, Article
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView


# def home(request, page=1):
#     # context = {
#     #     "articles": Article.objects.filter(status='p')
#     # }
#     # context = {
#     #     "articles": Article.objects.published()
#     # }
#     articles = Article.objects.published()
#     paginator = Paginator(articles, 2)
#     # page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page)
#     return render(request, "blog3/home.html", {"articles": page_obj})

class ArticleList(ListView):
    # model = Article
    # template_name = "blog3/article_list.html"
    # context_object_name = "object_list"
    queryset = Article.objects.published()
    paginate_by = 2


# def article_details(request, slug='Kentia_Palm_Plant'):
#     # try:
#     #     article = Article.objects.get(slug=slug)
#     # except Exception as e:
#     #     raise Http404
#     context = {
#         # "article": get_object_or_404(Article, slug=slug, status='p')
#         "article": get_object_or_404(Article.objects.published(), slug=slug)
#     }
#     return render(request, 'blog3/detail.html', context)


class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles = category.articles.published()
#     paginator = Paginator(articles, 2)
#     # page = request.GET.get('page')
#     articles = paginator.get_page(page)
#     context = {
#         # "category": get_object_or_404(Category, slug=slug, status=True)
#         # get_object_or_404(Category.objects.active_category(), slug=slug)
#         "category": category,
#         "articles": articles
#     }
#     return render(request, 'blog3/category_list.html', context)


class CategoryList(ListView):
    template_name = 'blog3/category_list.html'
    paginate_by = 2

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active_category(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

# class CategoryList(ListView):
#     paginate_by = 2
#     template_name = 'blog3/category_list.html'
#
#     def get_queryset(self):
#         slug = self.kwargs.get('slug')
#         category = get_object_or_404(Category.objects.active_category(), slug=slug)
#         return category.articles.published()


class AuthorList(ListView):
    template_name = 'blog3/author_list.html'
    paginate_by = 2

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

templates/blog3/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog3/article_detail.html
{% extends 'blog3/base.html' %}
{% load static %}
{% block title%} {{article.title}}| {% endblock %}
{% block custome-header %}
<link rel="stylesheet" type="text/css" href="red.css">
{% endblock %}

{% block main %}
<!-- Page Header-->
        <header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{object.title}}</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{object.description|safe}}
            </div>
        </div>
    </div>
</article>
{% endblock %}

templates/blog3/article_list.html
{% extends 'blog3/list.html' %}
{% load static %}
{% block site_heading %}
    <div class="site-heading">
        <h1>سیلسیم</h1>
    </div>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog3:home' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog3:home' page_obj.next_page_number %}
{% endblock %}

templates/blog3/author_list.html
{% extends 'blog3/list.html' %}
{% load static %}
{% block site_heading %}
    <div class="site-heading">
        <h1>لیست مقالات نویسندگان</h1>
    </div>
{% endblock %}

{% block category_title %}
    <h4 class="alert alert-primary text-center">نویسنده: {{author.get_full_name}}</h4>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog3:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog3:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog3/base.html
<!DOCTYPE html>
{% load static %}
{% load base_tags %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title%}{% endblock %}پروژه تست جنگو</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog3/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog3/css/rtl.css' %}" rel="stylesheet" />
        {% block custome-header %}
        {% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog3:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    {% category_navbar %}
                </div>
            </div>
        </nav>

        {% block main %}
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog3/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog3/category_list.html
{% extends 'blog3/list.html' %}
{% load static %}
{% block site_heading %}
    <div class="site-heading">
        <h1>mehrafarin weblog</h1>
    </div>
{% endblock %}

{% block category_title %}
    <h4 class="alert alert-primary text-center">دسته‌بندی: {{category.title}}</h4>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog3:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog3:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog3/list.html
{% extends 'blog3/base.html' %}
{% load static %}
{% block main %}
<!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'blog3/assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7 p-custome">
                        {% block site_heading %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% block category_title %}{% endblock %}
                    {% for article in object_list %}
                        <!-- Post preview-->
                        <div class="post-preview">
                            <a href="{% url 'blog3:article_details' article.slug %}">
                                <h2 class="post-title">{{article.title}}</h2>
                                <h3 class="post-subtitle">{{article.description|striptags|truncatewords:30}}</h3>
                            </a>
                            <p class="post-meta">
                                نوشته شده توسط
                                <a href="{% url 'blog3:author' article.author %}">{{article.author.get_full_name}}</a>
                                {{article.persian_publish_date}}
                            </p>
                            <div>
                                {% for cat in article.category.active_category %}
                                    <a href="{% url 'blog3:category' cat.slug %}">#{{cat.title}}</a>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endfor %}

                    {% if is_paginated %}
                        <div class="d-flex justify-content-end mb-4">
                            {% if page_obj.has_previous %}
                                <a class="btn btn-primary text-uppercase old_post"
                                   href="{% block previous_page_url %}{% endblock %}">
                                    پست‌های قدیمی →
                                </a>
                            {% endif %}

                            {% if page_obj.has_next %}
                                <a class="btn btn-primary text-uppercase"
                                   href="{% block next_page_url %} {% endblock %}">
                                    پست‌های جدید →</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}